
apiVersion: v1
kind: Service
metadata:
  name: orch-grpc-deployment-service
  namespace: petch
spec:
  selector:
    app: orch-grpc-deployment-deploy
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP